server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: deepseek_route
          uri: https://api.deepseek.com  # 目标地址写在这里
          predicates:
            - Path=/v1/chat/** # 拦截规则
#          filters:
#            - name: DeepSeekAuth

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/halo_cloud_db
    username: halo_user
    password: halo_password
data:
  redis:
    host: localhost  # 在 Codespace 里，Docker 端口会映射到 localhost
    port: 6379
    database: 0