server:
  port: 8081

spring:
  ai:
    openai:
      # 指向你的 Gateway 地址
      base-url: http://localhost:8080
      # 这里填什么都可以，Gateway 那边会拦截并替换成真的 DeepSeek Key
      api-key: internal-sidecar-token
      chat:
        options:
          model: deepseek-chat
